# Generated by Django 4.2.7 on 2023-11-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_created_by_product_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_by',
        ),
    ]
