# Generated by Django 4.2.7 on 2023-11-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_deleted_at_product_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashBin',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.product', verbose_name='Продукт в корзине')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Мусорная корзина',
                'verbose_name_plural': 'Мусорные корзины',
            },
        ),
    ]
