# Generated by Django 4.2.7 on 2023-11-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trashbin',
            options={'verbose_name': 'Мусорная корзина', 'verbose_name_plural': 'Мусорная корзины'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is_active'),
        ),
    ]
